### ISSUE TITLE
[BUG] New ZIM is deleted even though downloaded and checksum succeded

### ISSUE THREAD

**Issue by hboyd2003** [jojo2357/kiwix-zim#32]
When using the verify library flag (-f) and the size verification of a ZIM fails, the lock file of the new ZIM is not deleted causing the new ZIM to be deleted even though the download succeed and checksum passed.
![Animation](https://github.com/jojo2357/kiwix-zim/assets/8950185/7f26db3e-dcc7-4bfc-830c-1dfc248a5fe8)

**Comment by jojo2357** [comment]
I have replicated this issue, thank you for the detailed walkthrough

**Comment by jojo2357** [comment]
@hboyd2003 please verify that #33 solves your problem

**Comment by hboyd2003** [comment]
@jojo2357 It does thank you!
