### ISSUE TITLE
Purge Zims Right After Update

### ISSUE THREAD

**Issue by jojo2357** [jojo2357/kiwix-zim#7]
I have a fairly large library which I updated (so awesome btw)

I did some by hand before discovering the script, but I still had

```
69.3G
44.5G
30.5G
21.9G
15.5G
31.2G
~5G
```

~= 220G

And the script skipped Wikipedia (~93G) which I had done by hand.

The issue I barely missed? Running out of disk space. The script downloaded all the new zims and *then* removed the old ones. I think it would be better to download one, delete one, download one, delete, etc. That way I would (in the worst case) have needed 93G instead of 310G of free disk.

**Comment by DocDrydenn** [comment]
Good suggestion and I see your point. Let me see what I can do.
